PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS Users (
user_id INTEGER PRIMARY KEY,
username TEXT UNIQUE NOT NULL,
salt_password BLOB NOT NULL,
email TEXT UNIQUE,
is_admin INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Clock (
user_id,
clock_in TEXT NOT NULL,
clock_out TEXT,
comment TEXT,
FOREIGN KEY(user_id) REFERENCES User(user_id) ON DELETE CASCADE ON UPDATE CASCADE
);